#!/usr/bin/env python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'website.settings'
import argparse
import shutil
from website.passwords.models import Dumps


def run(stat_file):
    stat_name = os.path.basename(stat_file)
    output_file = os.path.join('website/static/stats', stat_name)
    try:
        d = Dumps.objects.get(name=stat_name)
        d.stat_file = output_file.lstrip('website')
        d.save()
        shutil.copyfile(stat_file, output_file)
    except:exit('\n\t[ERROR] no dump.name: %s\n' % stat_name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("statfile", help="path to stat file")
    args = parser.parse_args()
    run(args.statfile)
