#!/usr/bin/env python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'website.settings'
import django
import shutil
import argparse
from website.passwords.models import Dumps


def run(hashfile, dumpname, hashtype):
    hash_file = os.path.join('website/static/hashes', dumpname)
    password_file = os.path.join('website/static/passwords', dumpname)
    d, created = Dumps.objects.get_or_create(
        name=dumpname,
        hashtype=hashtype)
    try:d.save()
    except django.db.utils.IntegrityError:pass
    count = 0
    for hash_string in open(hashfile, 'r'):
        count += 1
    d.hash_count=count
    d.cracked = 0
    d.hash_file = hash_file
    d.password_filge = password_file
    d.save()
    shutil.copyfile(hashfile, hash_file)
    shutil.copyfile(hashfile, password_file)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("hashfile", help="path to hash file")
    parser.add_argument("dumpname", help="name of hash dump")
    parser.add_argument("hashtype", help="hash type of hash dump")
    args = parser.parse_args()
    run(args.hashfile, args.dumpname, args.hashtype)
