#!/usr/bin/env python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'website.settings'
import sys
import argparse
from website.passwords.models import Dumps


def run(input_file):
    hashes = {}
    output_file = os.path.join('website/static/passwords', input_file)
    try:f = open(output_file, 'r')
    except:exit('[ERROR] no file exists: %s' % pf)
    for line in f:
        hashes[line.rstrip('\r\n')] = 1
    for line in open(input_file, 'r'):
        hashstring = line[:line.index(":")]
        try:
            del hashes[hashstring]
            hashes[line.rstrip('\r\n')] = 0
        except KeyError:
            try:
                del hashes[line.rstrip('\r\n')]
                hashes[line.rstrip('\r\n')] = 0
            except:pass
    f = open(output_file, 'w+')
    hash_count = 0
    cracked = 0
    for line in hashes:
        hash_count += 1
        try:
            line.index(':')
            cracked += 1
        except ValueError:pass
        f.write('%s\r\n' % line)
    f.close()
    d = Dumps.objects.get(name=input_file)
    d.hash_count = hash_count
    d.cracked = cracked
    d.save()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("passwordfile", help="path to password file")
    args = parser.parse_args()
    run(args.passwordfile)
