#!/usr/bin/env python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'website.settings'
import argparse
from django.db.models import Q
from website.passwords.models import Dumps
from website.passwords.models import Passwords

def run(passwordfile):
    for line in open(passwordfile, 'r'):
        try:
            split_index = line.index(":")
            hashstring = line[:split_index]
            password = line[split_index + 1:].rstrip('\r\n')
            p = Passwords.objects.get(hashstring=hashstring)
            p.password = password.rstrip('\r\n')
            p.save()
        except ValueError:
            print line
            print '[ERROR] invalid file format'
    for dump in Dumps.objects.all():
        p = Passwords.objects.filter(dump=dump)
        dump.cracked = p.filter(~Q(password='')).count()
        dump.save()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("passwordfile", help="path to password file")
    args = parser.parse_args()
    run(args.passwordfile)
