#!/usr/bin/env python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'website.settings'
import django
import argparse
from website.passwords.models import Dumps
from website.passwords.models import Passwords

def run(hashfile, dumpname, hashtype):
    d, created = Dumps.objects.get_or_create(dump=dumpname, hashtype=hashtype)
    try:d.save()
    except django.db.utils.IntegrityError:pass
    p = []
    for hash_string in open(hashfile, 'r'):
        p.append(Passwords(hashstring=hash_string.rstrip('\r\n'), dump=d, password=''))
        if len(p) > 10000:
            Passwords.objects.bulk_create(p)
            del p[:]

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("hashfile", help="path to hash file")
    parser.add_argument("dumpname", help="name of hash dump")
    parser.add_argument("hashtype", help="hash type of hash dump")
    args = parser.parse_args()
    run(args.hashfile, args.dumpname, args.hashtype)
